export default function DetailBody() {
  return (
    <div className="detail-body-container">
        <div className="detail-title-container">
            <h3 className="detail-title">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium perspiciatis dolorum quia est veniam voluptatem</h3>
        </div>
        <div className="detail-text-container">
            <p className="detail-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem voluptate sapiente voluptatibus sed accusantium ipsum impedit similique magnam fuga dolor aliquam vel nam praesentium fugiat deleniti, doloremque repellendus. Incidunt natus aliquam eius soluta deserunt repellendus veritatis provident, nisi, ratione mollitia vero nam praesentium explicabo sunt suscipit temporibus cum eos molestiae possimus iure saepe tempore pariatur maiores! Reprehenderit iure voluptatem accusamus possimus natus? Modi, quibusdam. Fuga saepe itaque similique repellendus ex dolores consequatur repudiandae, minus magnam sunt nulla corrupti ad asperiores dolorum earum inventore placeat soluta, voluptate hic dignissimos natus maiores fugiat possimus. Dolores nam accusamus saepe, ad natus veniam facilis aliquam molestiae, reiciendis odio labore explicabo repellat, dignissimos sequi possimus voluptatem veritatis consectetur error vitae officia neque. Omnis odio, ipsum perspiciatis repellendus voluptate tempora eaque maxime esse? Voluptatem, eos cum? Asperiores ducimus distinctio vel architecto? Excepturi accusantium repudiandae vitae dolores illo ipsa sunt esse earum reprehenderit ut perferendis nemo nam dolorem error corporis iste, atque voluptatem, harum modi officia nulla obcaecati officiis amet repellat. Voluptates at, sapiente nemo magni aspernatur qui et nihil totam dolorum. Mollitia rem repellendus officiis qui fugiat eveniet saepe assumenda dolorem? Necessitatibus doloribus, dignissimos quos natus animi, mollitia repudiandae aperiam itaque enim nobis sunt consectetur harum corporis repellat.

Voluptatibus voluptatem perspiciatis corporis iure consequuntur nisi quia a voluptate aut, commodi inventore eum! Minus ratione est reiciendis delectus eligendi nemo fuga magni aliquam obcaecati accusantium maxime laudantium cum deserunt, quo accusamus dolor magnam voluptates. Amet repellendus vitae molestias. Alias, necessitatibus nesciunt laborum nihil, nobis quas non animi, ab dolorum blanditiis sapiente veritatis neque saepe maxime molestiae adipisci eius. Expedita cumque quas numquam, doloribus quo atque! Inventore natus animi veniam. Asperiores labore deleniti facilis, pariatur adipisci quibusdam. Nostrum quibusdam vel quasi sequi, officiis velit recusandae vero dignissimos autem soluta sapiente sed optio alias rerum deleniti aliquid dolore aspernatur explicabo laudantium? Tempora, dolor perspiciatis distinctio porro quae ratione deserunt, magnam consequatur excepturi labore vel veritatis dolores aspernatur optio asperiores sapiente reprehenderit a autem corporis iure iste ex? Commodi in dolores necessitatibus! Voluptatibus, laboriosam culpa corrupti ratione nemo delectus voluptates ipsum assumenda et vel autem praesentium voluptatum blanditiis esse sed provident eos officia sunt eum dolorum. Quo accusantium harum, sunt, dolorem unde esse enim eos delectus modi repudiandae ipsam reprehenderit vel eius, saepe quam voluptatem doloribus accusamus tempore adipisci sint voluptates voluptatibus quia nam.

Tenetur provident sint sunt blanditiis quo sed, in quibusdam culpa doloremque facere maxime, recusandae dolorem soluta expedita tempora? Ipsum optio itaque molestiae, numquam eos vel maiores facilis fuga dolorum laborum nemo impedit recusandae excepturi? Illo, modi odio. Iste consequuntur aspernatur sed ad rerum. Fuga alias eaque ipsa laudantium, itaque expedita laboriosam consequuntur unde nam esse nisi eius recusandae, nemo exercitationem animi dolore? Consectetur at optio saepe similique! Reprehenderit magni deleniti, iusto, labore ea odio repellat maxime voluptates sint explicabo eligendi delectus porro saepe! Dicta perspiciatis repudiandae dolore voluptas dolor inventore tempora nostrum placeat, quasi et consequuntur rem illum voluptatem expedita iure excepturi eligendi, est veritatis impedit cumque. Dolorem enim quasi fugit sint amet, sapiente accusantium, vero ea nemo aperiam nam molestiae laborum, accusamus temporibus culpa necessitatibus. Dolores voluptatibus velit reiciendis accusamus quaerat rerum odio sint consequuntur ducimus unde. Dolore et aperiam repudiandae cumque ratione vel explicabo dolorum maiores nisi ex, assumenda fugiat illum quia unde odit, amet itaque aliquid sit praesentium labore veniam distinctio possimus qui. Voluptatum nulla ratione sint atque placeat aliquid amet repellendus dolore quas mollitia minima, quaerat porro quod maxime suscipit rerum eius minus. Obcaecati atque doloremque a, tenetur accusantium architecto earum ipsa omnis? Veritatis suscipit debitis dignissimos qui nemo, itaque autem incidunt excepturi dolore quasi, tempora consectetur animi ad. Tempore pariatur cupiditate sapiente facere, harum adipisci, recusandae sunt eligendi, qui ullam error saepe! Fugiat obcaecati expedita dolor eum, amet culpa error sint impedit rerum hic aliquid officia tempora, nobis maxime non possimus voluptatem ipsa sit soluta nam doloribus provident blanditiis commodi perferendis! Ullam necessitatibus explicabo praesentium iure ad, dignissimos ipsa cupiditate vitae voluptatibus saepe atque, sapiente facere. Ea reiciendis, magnam id autem ullam velit illum sed molestias soluta in suscipit minima minus inventore! Dignissimos voluptatem veritatis modi illum non saepe odio ratione excepturi beatae totam, qui eum porro, error aliquam et animi earum. Eligendi repellat magnam nostrum dolorum exercitationem sequi ea eveniet blanditiis alias magni. Tenetur libero laudantium fugit illum fugiat! Cupiditate, qui? Quam officia eum necessitatibus, in commodi ducimus corporis repellat iure architecto.</p>
        </div>
        <div className="detail-thumb-container">
            <div className="detail-thumb-up-container">
                <div className="detail-thumb-up-icon"></div>
                <div className="detail-thumb-up-text">0</div>
            </div>
            <div className="detail-thumb-down-container">
                <div className="detail-thumb-down-icon"></div>
                <div className="detail-thumb-down-text">0</div>
            </div>
        </div>
    </div>
  );
}
